### ISSUE TITLE
Autocompletion for methods in dataProvider annotations

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-phpunit-plugin#21]
It would be great if the plugin could provide autocompletion when writing the `@dataProvider` annotation on a test.

**Comment by King2500** [comment]
Actually PhpStorm already does this for me:
![image](https://user-images.githubusercontent.com/4896363/28972284-5c2959d0-792f-11e7-949e-820253918af0.png)

It's a long list when nothing further is typed, because every global function is also listed. I think that's correct, but not commonly used in this case.

**Comment by stof** [comment]
Well, global functions are right there, as data providers can either be class methods or callable (you could also do `TestBuilder::getFiles` btw).

For some reasons, PhpStorm was not properly completing things when I was writing my tests a few hours ago, but it does now. very weird.

I'm closing this issue.

**Comment by stof** [comment]
@King2500 FYI, I just opened https://youtrack.jetbrains.com/issue/WI-37542 to request a smarter sorting of completion suggestions there
